DxCx/plugin.video.wonderfulsubs

- default.py
original history delim was effecting search results
> fixes search not working

- resources/lib/ui/control.py
-loads HLS faster
-helps buffering/stuttering issue users are experiencing with HLS server
-allows users to manually change HLS res by configuring inputstream adaptive
> adds hook for HLS

- resources/lib/WonderfulSubsBrowser.py
Before https://github.com/DxCx/plugin.video.wonderfulsubs/pull/29/commits/061cf9a770755651f170e16531c8946b686c2c25:
After commit:
> anime_seasons iconimage and plot

- default.py
- resources/lib/WatchlistIntegration.py
- resources/lib/WonderfulSubsBrowser.py
- resources/settings.xml
option to select only sub or dub anime to show up in addon. 
remembered users in discord feedback requested option when beta version was initially released
> adds option to filter anime flavor

- README.md
~~todo: replace current discord link with link provided by~~
link updated
> adds discord link to readme

- default.py
- resources/lib/WatchlistFlavor/__init__.py
- resources/lib/ui/utils.py
- resources/settings.xml
this fixes autoplay always playing dash/hls source, when 1080p, 720p, ... is selected as preferred res
> adds parse resolution for dash and hls source

- resources/lib/WatchlistFlavor/WonderfulSubs.py
- resources/settings.xml
fixes #36 
Adds setting in wonderfulsubs watchlist settings section to filter anime flavor
> fix: Filter Dub/Sub ignores setting on watchlist from WonderfulSubs

- default.py
- resources/lib/ui/control.py
- resources/settings.xml
[as suggested in discord](https://discordapp.com/channels/386361030353354765/555098164357758976/563432129682210836)
references used: https://forum.kodi.tv/showthread.php?tid=116496&pid=1518450#pid1518450 and https://forum.kodi.tv/showthread.php?tid=116496&pid=1518727#pid1518727
> adds clear cache button

- resources/lib/WatchlistFlavor/AniList.py
> fixes anilist sort by 'last updated' (issue #51)

- resources/lib/WonderfulSubsBrowser.py
[as suggested in discord](https://discordapp.com/channels/386361030353354765/540024225646510090/569385986224685056)
> removes the (Sub)/(Dub) part of the title, when anime flavor is filtered

- default.py
- resources/lib/ui/control.py
- resources/settings.xml
as suggested in discord
> Kodi can we have an option to auto update MAL instead of asking me Everytime I finish an episode?
> update watchlist when set watched percentage is reached

- resources/lib/ui/control.py
> fixes on precentage update (issue #57)

- resources/settings.xml
accidentally removed filter in setting when resolving conflict for on-percent PR
> re-add filter in setting for wonderfulsubs watchlist

- resources/lib/WatchlistFlavor/MyAnimeList.py
> fixes update on MAL after watched doesn't work (issue #55)

- resources/lib/ui/embed_extractor.py
can go back to this since rapidvideo brought back qualities for non premium users
> fixes fetching sources hanging

- default.py
- resources/settings.xml
> adds ability to set seasons and episodes content type

- resources/lib/WatchlistFlavor/AniList.py
- resources/lib/WatchlistFlavor/Kitsu.py
- resources/lib/WatchlistFlavor/MyAnimeList.py
- resources/lib/WatchlistFlavor/WatchlistFlavorBase.py
- resources/lib/WatchlistFlavor/WonderfulSubs.py
- resources/settings.xml
also cleaned up some code in other watchlist flavors.
added directions in wiki to get anilist access token https://github.com/DxCx/plugin.video.wonderfulsubs/wiki/Get-AniList-Access-Token
> adds anilist watchlist updating

- resources/lib/ui/embed_extractor.py
refactors rapidvideo extractor
> fixes missing qualities

- default.py
- resources/lib/AniListBrowser.py
- resources/lib/GogoAnimeBrowser.py
- resources/lib/WatchlistIntegration.py
- resources/lib/WonderfulSubsBrowser.py
- resources/lib/ui/control.py
- resources/lib/ui/embed_extractor.py
- resources/lib/ui/utils.py
helpful when anime movies/ovas don't work or having problems playing episode sources
example: https://streamable.com/m01p9
thanks to gogoanime and mp4upload code from github user vn-ki (anime-downloader)
> adds alternative anime search in context menu

- resources/lib/ui/embed_extractor.py
> fixes 'couldn't find eligible sources' (#95)

- resources/lib/ui/embed_extractor.py
fixes search alt 'not finding eligible sources' error by adding new domains
> fixes search alt 'not finding eligible sources' error

- default.py
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.he_il/strings.po
- resources/lib/WatchlistFlavor/WonderfulSubs.py
- resources/lib/WatchlistFlavor/__init__.py
- resources/lib/WatchlistIntegration.py
- resources/lib/WonderfulSubsBrowser.py
- resources/lib/constants.py
- resources/lib/ui/BrowserBase.py
- resources/lib/ui/embed_extractor.py
- resources/lib/ui/http.py
- resources/settings.xml
1. Move base url and api base into own module
2. Use new api base where applicable
3. login to wonderful subs by default
Closes #134
> Move to api version 2 [Thanks @nalch]
